import type { QuizQuestion } from "./types";

export type Blanc = {
  id: string;
  title: string;
  durationMin: number;
  description: string;
  questions: QuizQuestion[];
};

export const BLANCS: Blanc[] = [
  {
    id: "blanc-1",
    title: "Sujet blanc 1 — conditions d’examen",
    durationMin: 180,
    description:
      "24 questions, 4 matières. Traite-les sans notes. Vise ≥ 16/24 avant samedi.",
    questions: [
      {
        id: "bl1-1",
        question: "C — int i = 5; printf(\"%d %d\", i++, ++i);  Comportement ?",
        options: [
          "Affiche toujours 5 7",
          "Affiche toujours 6 6",
          "Undefined behavior (deux modifications de i sans point de séquence)",
          "Erreur de compilation obligatoire",
        ],
        answer: 2,
        explain:
          "Modifier i deux fois dans le même appel est UB. Au concours, signale l’UB plutôt que d’inventer un affichage.",
      },
      {
        id: "bl1-2",
        question: "C — Complexité pire cas du tri par insertion ?",
        options: ["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"],
        answer: 2,
        explain: "Tableau trié à l’envers : chaque insertion décale tout le préfixe.",
      },
      {
        id: "bl1-3",
        question: "C — Pour échanger deux int x,y on écrit",
        options: ["swap(x,y) par valeur", "swap(&x,&y) avec int*", "x,y = y,x", "*swap(x,y)"],
        answer: 1,
        explain: "Passage par adresse.",
      },
      {
        id: "bl1-4",
        question: "C — strlen(\"AB\") et sizeof(\"AB\") valent",
        options: ["2 et 2", "2 et 3", "3 et 3", "2 et 4"],
        answer: 1,
        explain: "strlen ignore '\\0' ; sizeof le compte (et le littéral a 3 chars).",
      },
      {
        id: "bl1-5",
        question: "C — t[i] est équivalent à",
        options: ["t+i", "*(t+i)", "&t + i", "t[i++] toujours"],
        answer: 1,
        explain: "Définition de l’indexation.",
      },
      {
        id: "bl1-6",
        question: "C — malloc(n * sizeof *p) suivi de rien. Risque principal ?",
        options: ["overflow signé", "fuite si on oublie free + dangling si free trop tôt", "erreur de type", "RR"],
        answer: 1,
        explain: "Heap = responsabilité du programmeur.",
      },
      {
        id: "bl1-7",
        question: "SQL — Filtrer les groupes de moyenne ≥ 12 :",
        options: ["WHERE AVG(note) >= 12", "HAVING AVG(note) >= 12", "ON AVG(note)", "LIMIT 12"],
        answer: 1,
        explain: "HAVING après GROUP BY.",
      },
      {
        id: "bl1-8",
        question: "SQL — Étudiants sans inscription :",
        options: [
          "INNER JOIN",
          "LEFT JOIN Inscription + WHERE i.numE IS NULL",
          "HAVING COUNT > 0",
          "UNION",
        ],
        answer: 1,
        explain: "Anti-jointure.",
      },
      {
        id: "bl1-9",
        question: "Relationnel — Une DF X→Y signifie",
        options: [
          "X et Y disjoints",
          "égalité sur X ⇒ égalité sur Y",
          "X est une FK",
          "Y est NULL",
        ],
        answer: 1,
        explain: "Définition de la dépendance fonctionnelle.",
      },
      {
        id: "bl1-10",
        question: "3NF interdit principalement",
        options: [
          "les FK",
          "les DF transitives de non-clé vers non-clé",
          "les jointures",
          "COUNT(*)",
        ],
        answer: 1,
        explain: "Après 2NF, on chasse les transitives.",
      },
      {
        id: "bl1-11",
        question: "Algèbre — « tous les modules » se traduit par",
        options: ["σ", "π", "division (ou double NOT EXISTS)", "∪"],
        answer: 2,
        explain: "Quantificateur universel.",
      },
      {
        id: "bl1-12",
        question: "SQL — COUNT(col) ignore",
        options: ["les 0", "les NULL", "les doublons toujours", "les PK"],
        answer: 1,
        explain: "COUNT(*) ne les ignore pas.",
      },
      {
        id: "bl1-13",
        question: "Stats — Variance d’échantillon sans biais : on divise par",
        options: ["n", "n-1", "n+1", "√n"],
        answer: 1,
        explain: "Bessel.",
      },
      {
        id: "bl1-14",
        question: "P(A|B) =",
        options: ["P(A)P(B)", "P(A∩B)/P(B)", "P(A)+P(B)", "P(B|A)"],
        answer: 1,
        explain: "Définition.",
      },
      {
        id: "bl1-15",
        question: "X ~ N(μ,σ²), Z = (X−μ)/σ suit",
        options: ["N(μ,1)", "N(0,1)", "t_n", "U[0,1]"],
        answer: 1,
        explain: "Loi normale centrée réduite.",
      },
      {
        id: "bl1-16",
        question: "IC 95 % σ connu : x̄ ±",
        options: ["1,64 σ/√n", "1,96 σ/√n", "2,58 s", "σ/n"],
        answer: 1,
        explain: "z = 1,96.",
      },
      {
        id: "bl1-17",
        question: "On rejette H0 (bilatéral 5 %) si",
        options: ["|z| < 1,96", "|z| > 1,96", "p > 0,05", "n < 30"],
        answer: 1,
        explain: "Région critique.",
      },
      {
        id: "bl1-18",
        question: "R² = 0,81 ⇒ |r| =",
        options: ["0,81", "0,9", "0,405", "1,81"],
        answer: 1,
        explain: "R² = r².",
      },
      {
        id: "bl1-19",
        question: "−1 en complément à 2 sur 8 bits",
        options: ["10000001", "11111111", "00000001", "10000000"],
        answer: 1,
        explain: "Tous les bits à 1.",
      },
      {
        id: "bl1-20",
        question: "AMAT =",
        options: ["T_hit × miss", "T_hit + miss_rate × T_miss", "T_miss − T_hit", "CPI"],
        answer: 1,
        explain: "Formule standard.",
      },
      {
        id: "bl1-21",
        question: "Round Robin avec q → ∞ tend vers",
        options: ["SJF", "FCFS", "SRTF", "banquier"],
        answer: 1,
        explain: "Plus de préemption.",
      },
      {
        id: "bl1-22",
        question: "TLB miss ≠ page fault car",
        options: [
          "c’est la même chose",
          "la page peut être en RAM, seule la traduction n’est pas dans le TLB",
          "le TLB est sur disque",
          "FIFO",
        ],
        answer: 1,
        explain: "Distinction classique.",
      },
      {
        id: "bl1-23",
        question: "Threads d’un même processus partagent",
        options: ["leurs piles", "l’espace d’adressage", "leurs PC", "rien du tout"],
        answer: 1,
        explain: "Piles privées, mémoire globale partagée.",
      },
      {
        id: "bl1-24",
        question: "Coffman : pour empêcher un deadlock il suffit de casser",
        options: ["les 4 conditions", "au moins 1 des 4", "le quantum", "le TLB"],
        answer: 1,
        explain: "Les 4 sont nécessaires.",
      },
    ],
  },
  {
    id: "blanc-2",
    title: "Sujet blanc 2 — salve rapide",
    durationMin: 45,
    description: "16 questions, rythme concours. Idéal vendredi soir après les fiches.",
    questions: [
      {
        id: "bl2-1",
        question: "scanf(\"%d\", n) sans & :",
        options: ["correct", "undefined / crash probable", "lit un float", "rien"],
        answer: 1,
        explain: "Il faut l’adresse.",
      },
      {
        id: "bl2-2",
        question: "Recherche binaire requiert un tableau",
        options: ["plein de 0", "trié", "alloué par malloc", "de taille 2^k"],
        answer: 1,
        explain: "Invariant d’ordre.",
      },
      {
        id: "bl2-3",
        question: "7/2 en int C =",
        options: ["3.5", "3", "4", "2"],
        answer: 1,
        explain: "Division entière.",
      },
      {
        id: "bl2-4",
        question: "Quicksort pire cas",
        options: ["O(n log n)", "O(n²)", "O(n)", "O(1)"],
        answer: 1,
        explain: "Pivot toujours extrême.",
      },
      {
        id: "bl2-5",
        question: "PK peut-elle être NULL ?",
        options: ["oui", "non", "si composite", "en 3NF"],
        answer: 1,
        explain: "Unicité + non nullité.",
      },
      {
        id: "bl2-6",
        question: "SELECT ville, COUNT(*) FROM Etu; sans GROUP BY est",
        options: ["correct ANSI", "illégal (ville non agrégée)", "un JOIN", "une vue"],
        answer: 1,
        explain: "Règle du GROUP BY.",
      },
      {
        id: "bl2-7",
        question: "LIKE 'M%' trouve",
        options: ["finit par M", "commence par M", "contient M au milieu seulement", "M unique"],
        answer: 1,
        explain: "% = joker.",
      },
      {
        id: "bl2-8",
        question: "Une association N-N devient",
        options: ["une FK unique", "une table (id1, id2, …)", "une fusion", "un index"],
        answer: 1,
        explain: "Table de liaison.",
      },
      {
        id: "bl2-9",
        question: "V(aX+b) =",
        options: ["a V(X)+b", "a² V(X)", "V(X)+b", "a V(X)"],
        answer: 1,
        explain: "Constante disparait, a au carré.",
      },
      {
        id: "bl2-10",
        question: "B(n,p) : E[X] =",
        options: ["p", "np", "np(1-p)", "n"],
        answer: 1,
        explain: "n Bernoulli.",
      },
      {
        id: "bl2-11",
        question: "p-valeur < α",
        options: ["accepter H0", "rejeter H0", "augmenter n", "σ=0"],
        answer: 1,
        explain: "Décision du test.",
      },
      {
        id: "bl2-12",
        question: "Médiane vs moyenne : la médiane est",
        options: ["plus sensible aux outliers", "plus robuste aux outliers", "toujours égale", "σ"],
        answer: 1,
        explain: "Robustesse.",
      },
      {
        id: "bl2-13",
        question: "0xFF =",
        options: ["16", "255", "15", "256"],
        answer: 1,
        explain: "8 bits à 1.",
      },
      {
        id: "bl2-14",
        question: "Processus blocked :",
        options: ["il tourne", "il attend un événement (I/O, synchro)", "il est zombie", "il est en cache"],
        answer: 1,
        explain: "Waiting.",
      },
      {
        id: "bl2-15",
        question: "Pages 4 Ko, VA 32 bits : bits de n° de page",
        options: ["12", "20", "32", "10"],
        answer: 1,
        explain: "32−12=20.",
      },
      {
        id: "bl2-16",
        question: "Mutex = sémaphore initialisé à",
        options: ["0", "1", "n", "∞"],
        answer: 1,
        explain: "Exclusion binaire.",
      },
    ],
  },
];
