import type { PlanBlock } from "./types";

/** Crash plan — exam Saturday 19 Sept 2026 10:00. */
export const CRASH_PLAN: PlanBlock[] = [
  {
    id: "p1",
    date: "2026-09-15",
    start: "09:00",
    end: "12:00",
    subjectId: "algo-c",
    title: "C : bases → pointeurs",
    note: "Chapitres 1 à 5. Tracer 5 QCM à la main.",
  },
  {
    id: "p2",
    date: "2026-09-15",
    start: "14:00",
    end: "16:30",
    subjectId: "algo-c",
    title: "C : tris, listes, fiche",
    note: "Écrire swap, palindrome, insertion, binaire sans compilateur.",
  },
  {
    id: "p3",
    date: "2026-09-15",
    start: "17:00",
    end: "19:00",
    subjectId: "bdd",
    title: "Relationnel + algèbre",
    note: "Traduire 4 phrases en σ, π, ⋈.",
  },
  {
    id: "p4",
    date: "2026-09-16",
    start: "09:00",
    end: "12:00",
    subjectId: "bdd",
    title: "SQL jointures & agrégats",
    note: "WHERE vs HAVING. Anti-jointure. Double NOT EXISTS.",
  },
  {
    id: "p5",
    date: "2026-09-16",
    start: "14:00",
    end: "16:00",
    subjectId: "bdd",
    title: "Normalisation 3NF",
    note: "2 schémas complets avec DF, clé, décomposition.",
  },
  {
    id: "p6",
    date: "2026-09-16",
    start: "16:30",
    end: "19:00",
    subjectId: "stats",
    title: "Descriptif + probas + Bayes",
    note: "Formules s² et Bayes jusqu’à les écrire de mémoire.",
  },
  {
    id: "p7",
    date: "2026-09-17",
    start: "09:00",
    end: "12:00",
    subjectId: "stats",
    title: "Lois, IC, tests, régression",
    note: "z=1,96. Un test complet en 6 lignes. Droite MC.",
  },
  {
    id: "p8",
    date: "2026-09-17",
    start: "14:00",
    end: "17:30",
    subjectId: "archi",
    title: "Binaire, CPU, cache, AMAT",
    note: "10 conversions + 2 AMAT + cycle FDE.",
  },
  {
    id: "p9",
    date: "2026-09-17",
    start: "18:00",
    end: "20:00",
    subjectId: "archi",
    title: "Processus & ordonnancement",
    note: "Un Gantt FCFS, un SJF, un RR.",
  },
  {
    id: "p10",
    date: "2026-09-18",
    start: "09:00",
    end: "11:30",
    subjectId: "archi",
    title: "Pagination, synchro, fiche",
    note: "TLB vs page fault. Coffman. FIFO/LRU.",
  },
  {
    id: "p11",
    date: "2026-09-18",
    start: "13:30",
    end: "16:30",
    subjectId: "mix",
    title: "Sujet blanc 1 (3 h)",
    note: "Conditions d’examen. Corriger ensuite avec les solutions.",
  },
  {
    id: "p12",
    date: "2026-09-18",
    start: "17:00",
    end: "19:30",
    subjectId: "mix",
    title: "Fiches des 4 matières",
    note: "Chapitres 8 uniquement. Pièges, pas de nouveau cours.",
  },
  {
    id: "p13",
    date: "2026-09-19",
    start: "07:30",
    end: "09:00",
    subjectId: "mix",
    title: "Relecture légère",
    note: "Formules stats + patrons SQL + swap C. Petit déjeuner.",
  },
  {
    id: "p14",
    date: "2026-09-19",
    start: "10:00",
    end: "13:00",
    subjectId: "exam",
    title: "Épreuve — Amphi 5",
    note: "FSA Safi. Pièce d’identité. Arrive 30 min tôt.",
  },
];
