import type { Resource } from "./types";

export const RESOURCES: Resource[] = [
  {
    id: "f-algo",
    title: "Fiche express C / algo",
    kind: "fiche",
    subjectId: "algo-c",
    blurb: "15 pièges, squelettes swap / parcours / binaire, méthode QCM 40 s.",
    internalTo: "/matieres/algo-c/fiche",
    countLabel: "1 fiche",
  },
  {
    id: "f-bdd",
    title: "Fiche SQL + 3NF",
    kind: "fiche",
    subjectId: "bdd",
    blurb: "8 patrons SQL, WHERE vs HAVING, anti-jointure, division, normalisation.",
    internalTo: "/matieres/bdd/fiche",
    countLabel: "1 fiche",
  },
  {
    id: "f-stats",
    title: "Formulaire de statistique",
    kind: "fiche",
    subjectId: "stats",
    blurb: "Descriptif, Bayes, lois, IC, z-test, R². Quantiles 1,64 / 1,96 / 2,58.",
    internalTo: "/matieres/stats/fiche",
    countLabel: "1 fiche",
  },
  {
    id: "f-archi",
    title: "Fiche Archi / SE",
    kind: "fiche",
    subjectId: "archi",
    blurb: "Complément à 2, AMAT, Gantt, TLB vs page fault, Coffman.",
    internalTo: "/matieres/archi/fiche",
    countLabel: "1 fiche",
  },
  {
    id: "an1",
    title: "Sujet blanc 1 — 3 heures",
    kind: "annale",
    blurb: "Quatre parties calquées sur l’écrit SDA. QCM + exercices, corrigé détaillé.",
    internalTo: "/quiz/blanc-1",
    countLabel: "24 questions",
  },
  {
    id: "an2",
    title: "Sujet blanc 2 — mix rapide",
    kind: "annale",
    blurb: "Entraînement 45 min, une salve par matière pour le vendredi soir.",
    internalTo: "/quiz/blanc-2",
    countLabel: "16 questions",
  },
  {
    id: "l-c",
    title: "Référence C (cppreference)",
    kind: "lien",
    subjectId: "algo-c",
    blurb: "stdio, stdlib, string.h — à consulter si un détail de fonction manque.",
    href: "https://en.cppreference.com/w/c",
    countLabel: "Référence",
  },
  {
    id: "l-sql",
    title: "PostgreSQL — tutorial SQL",
    kind: "lien",
    subjectId: "bdd",
    blurb: "SELECT, JOIN, agrégats. Le dialecte du concours est du SQL standard.",
    href: "https://www.postgresql.org/docs/current/tutorial-sql.html",
    countLabel: "Doc",
  },
  {
    id: "div-exam",
    title: "Consignes du jour J",
    kind: "divers",
    blurb: "Samedi 19/09/2026, 10h00, Amphi 5, FSA Safi. Pièce d’identité, arrivée anticipée.",
    internalTo: "/planning",
    countLabel: "Rappel",
  },
];
