/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as MatieresRouteImport } from './routes/matieres'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RessourcesRouteImport } from './routes/ressources'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as MatieresSubjectIdRouteImport } from './routes/matieres_.$subjectId'
import { Route as QuizQuizIdRouteImport } from './routes/quiz_.$quizId'
import { Route as MatieresSubjectIdChapterIdRouteImport } from './routes/matieres_.$subjectId_.$chapterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const MatieresRoute = MatieresRouteImport.update({
  id: '/matieres',
  path: '/matieres',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RessourcesRoute = RessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const MatieresSubjectIdRoute = MatieresSubjectIdRouteImport.update({
  id: '/matieres_/$subjectId',
  path: '/matieres/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz_/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatieresSubjectIdChapterIdRoute =
  MatieresSubjectIdChapterIdRouteImport.update({
    id: '/matieres_/$subjectId_/$chapterId',
    path: '/matieres/$subjectId/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favoris': typeof FavorisRoute
  '/matieres': typeof MatieresRoute
  '/parametres': typeof ParametresRoute
  '/planning': typeof PlanningRoute
  '/quiz': typeof QuizRoute
  '/ressources': typeof RessourcesRoute
  '/statistiques': typeof StatistiquesRoute
  '/matieres/$subjectId': typeof MatieresSubjectIdRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/matieres/$subjectId/$chapterId': typeof MatieresSubjectIdChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favoris': typeof FavorisRoute
  '/matieres': typeof MatieresRoute
  '/parametres': typeof ParametresRoute
  '/planning': typeof PlanningRoute
  '/quiz': typeof QuizRoute
  '/ressources': typeof RessourcesRoute
  '/statistiques': typeof StatistiquesRoute
  '/matieres/$subjectId': typeof MatieresSubjectIdRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/matieres/$subjectId/$chapterId': typeof MatieresSubjectIdChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favoris': typeof FavorisRoute
  '/matieres': typeof MatieresRoute
  '/parametres': typeof ParametresRoute
  '/planning': typeof PlanningRoute
  '/quiz': typeof QuizRoute
  '/ressources': typeof RessourcesRoute
  '/statistiques': typeof StatistiquesRoute
  '/matieres_/$subjectId': typeof MatieresSubjectIdRoute
  '/quiz_/$quizId': typeof QuizQuizIdRoute
  '/matieres_/$subjectId_/$chapterId': typeof MatieresSubjectIdChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favoris'
    | '/matieres'
    | '/parametres'
    | '/planning'
    | '/quiz'
    | '/ressources'
    | '/statistiques'
    | '/matieres/$subjectId'
    | '/quiz/$quizId'
    | '/matieres/$subjectId/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favoris'
    | '/matieres'
    | '/parametres'
    | '/planning'
    | '/quiz'
    | '/ressources'
    | '/statistiques'
    | '/matieres/$subjectId'
    | '/quiz/$quizId'
    | '/matieres/$subjectId/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/favoris'
    | '/matieres'
    | '/parametres'
    | '/planning'
    | '/quiz'
    | '/ressources'
    | '/statistiques'
    | '/matieres_/$subjectId'
    | '/quiz_/$quizId'
    | '/matieres_/$subjectId_/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavorisRoute: typeof FavorisRoute
  MatieresRoute: typeof MatieresRoute
  ParametresRoute: typeof ParametresRoute
  PlanningRoute: typeof PlanningRoute
  QuizRoute: typeof QuizRoute
  RessourcesRoute: typeof RessourcesRoute
  StatistiquesRoute: typeof StatistiquesRoute
  MatieresSubjectIdRoute: typeof MatieresSubjectIdRoute
  QuizQuizIdRoute: typeof QuizQuizIdRoute
  MatieresSubjectIdChapterIdRoute: typeof MatieresSubjectIdChapterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matieres': {
      id: '/matieres'
      path: '/matieres'
      fullPath: '/matieres'
      preLoaderRoute: typeof MatieresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressources': {
      id: '/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof RessourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matieres_/$subjectId': {
      id: '/matieres_/$subjectId'
      path: '/matieres/$subjectId'
      fullPath: '/matieres/$subjectId'
      preLoaderRoute: typeof MatieresSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz_/$quizId': {
      id: '/quiz_/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matieres_/$subjectId_/$chapterId': {
      id: '/matieres_/$subjectId_/$chapterId'
      path: '/matieres/$subjectId/$chapterId'
      fullPath: '/matieres/$subjectId/$chapterId'
      preLoaderRoute: typeof MatieresSubjectIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavorisRoute: FavorisRoute,
  MatieresRoute: MatieresRoute,
  ParametresRoute: ParametresRoute,
  PlanningRoute: PlanningRoute,
  QuizRoute: QuizRoute,
  RessourcesRoute: RessourcesRoute,
  StatistiquesRoute: StatistiquesRoute,
  MatieresSubjectIdRoute: MatieresSubjectIdRoute,
  QuizQuizIdRoute: QuizQuizIdRoute,
  MatieresSubjectIdChapterIdRoute: MatieresSubjectIdChapterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
